-- ---------- Machines (generated by the data table below; 55 registered + 5 drafts = 60, SPEC §17) ----------
create table seed.machine_plan (slot int primary key, plan text, make text, model text, category public.machine_category, year int, hours int, serial text, scenarios text[]);
create table seed.machine_ids (slot int primary key, machine_id uuid not null);
insert into seed.machine_plan values
  (1, 'berg', 'JCB', '3CX', 'backhoe', 2023, 1743, 'JCB3CX04278', array['enc:bank:leasing','level2']::text[]),
  (2, 'berg', 'Liebherr', 'R 926', 'excavator_tracked', 2014, 12648, 'LHRR92630256', array['enc:bank:ownership_reservation','level2']::text[]),
  (3, 'berg', 'Kubota', 'KX080-4', 'excavator_tracked', 2023, 2574, 'KBTKX080489696', array['enc:finans:leasing','level2']::text[]),
  (4, 'berg', 'Caterpillar', '950 GC', 'wheel_loader', 2018, 2656, 'CAT0950GC78397', array['stolen']::text[]),
  (5, 'berg', 'Caterpillar', '320', 'excavator_tracked', 2015, 5918, 'CAT032013280', array['scrapped']::text[]),
  (6, 'berg', 'Caterpillar', '320', 'excavator_tracked', 2015, 11363, 'CAT032074563', array['transfer']::text[]),
  (7, 'berg', 'Liebherr', 'LTM 1060-3.1', 'crane_mobile', 2019, 6321, 'LHRLTM10629893', '{}'::text[]),
  (8, 'berg', 'Caterpillar', '140', 'grader', 2024, 926, 'CAT014001851', array['level2']::text[]),
  (9, 'berg', 'Volvo', 'ECR25 Electric', 'excavator_tracked', 2016, 4590, 'VCEECR25E45597', array['level2']::text[]),
  (10, 'berg', 'Volvo', 'A30G', 'dumper', 2013, 5122, 'VCEA30G45118', array['level1']::text[]),
  (11, 'berg', 'Toyota', '8FD30', 'forklift', 2017, 5868, 'TYT8FD3013676', array['level1']::text[]),
  (12, 'berg', 'Caterpillar', 'D6', 'dozer', 2023, 2310, 'CAT0D606695', '{}'::text[]),
  (13, 'lena', 'JCB', '3CX', 'backhoe', 2018, 3040, 'JCB3CX17361', array['enc:bank:ownership_reservation','new_sale']::text[]),
  (14, 'lena', 'JCB', '3CX', 'backhoe', 2025, 943, 'JCB3CX39427', array['level2']::text[]),
  (15, 'lena', 'JCB', '3CX', 'backhoe', 2021, 2480, 'JCB3CX48400', array['level1']::text[]),
  (16, 'kommun', 'Volvo', 'L120H', 'wheel_loader', 2022, 2132, 'VCEL120H07006', array['enc:finans:ownership_reservation','new_sale']::text[]),
  (17, 'kommun', 'Hamm', 'H 13i', 'roller', 2025, 538, 'HAMH13I11458', array['enc:bank:leasing','new_sale']::text[]),
  (18, 'kommun', 'Kubota', 'KX080-4', 'excavator_tracked', 2016, 7640, 'KBTKX080450823', array['stolen']::text[]),
  (19, 'kommun', 'Atlas Copco', 'XAS 188', 'compressor', 2017, 5967, 'ACXXAS18822319', array['blocked']::text[]),
  (20, 'kommun', 'Volvo', 'A30G', 'dumper', 2016, 10180, 'VCEA30G88841', array['scrapped']::text[]),
  (21, 'kommun', 'Volvo', 'L120H', 'wheel_loader', 2022, 1900, 'VCEL120H80840', array['level2']::text[]),
  (22, 'kommun', 'Liebherr', 'R 926', 'excavator_tracked', 2019, 4816, 'LHRR92622417', array['level1']::text[]),
  (23, 'kommun', 'Caterpillar', '140', 'grader', 2023, 2610, 'CAT014084886', array['level1']::text[]),
  (24, 'nordmaskin', 'Volvo', 'EW160E', 'excavator_wheeled', 2017, 9774, 'VCEEW160E90733', array['enc:finans:leasing','stock']::text[]),
  (25, 'nordmaskin', 'Komatsu', 'PC210LCi-11', 'excavator_tracked', 2025, 332, 'KMTPCPC210L31021', array['enc:bank:ownership_reservation','stock']::text[]),
  (26, 'nordmaskin', 'Epiroc', 'SmartROC T35', 'drill_rig', 2016, 3670, 'EPISMARTR53581', array['stock']::text[]),
  (27, 'nordmaskin', 'Volvo', 'A30G', 'dumper', 2023, 1866, 'VCEA30G75341', array['rented']::text[]),
  (28, 'nordmaskin', 'Volvo', 'A30G', 'dumper', 2019, 4935, 'VCEA30G86909', array['rented']::text[]),
  (29, 'nordmaskin', 'Komatsu', 'WA320-8', 'wheel_loader', 2016, 4420, 'KMTPCWA320819726', array['level2']::text[]),
  (30, 'nordmaskin', 'Liebherr', 'R 926', 'excavator_tracked', 2020, 5106, 'LHRR92698647', array['level2']::text[]),
  (31, 'nordmaskin', 'Caterpillar', 'D6', 'dozer', 2021, 3690, 'CAT0D698912', array['level2']::text[]),
  (32, 'nordmaskin', 'John Deere', '1210G', 'forestry_forwarder', 2015, 4851, '1YJ1210G48447', array['level1']::text[]),
  (33, 'nordmaskin', 'Ponsse', 'Buffalo', 'forestry_forwarder', 2024, 696, 'PONBUFFAL12915', '{}'::text[]),
  (34, 'nordmaskin', 'JCB', '3CX', 'backhoe', 2022, 1852, 'JCB3CX21033', '{}'::text[]),
  (35, 'nordmaskin', 'Volvo', 'ECR25 Electric', 'excavator_tracked', 2013, 9022, 'VCEECR25E79172', '{}'::text[]),
  (36, 'syd', 'Toyota', '8FD30', 'forklift', 2019, 5887, 'TYT8FD3079104', array['stock']::text[]),
  (37, 'syd', 'Caterpillar', 'D6', 'dozer', 2025, 311, 'CAT0D673512', array['stock']::text[]),
  (38, 'syd', 'JCB', '3CX', 'backhoe', 2020, 6408, 'JCB3CX90353', array['level2']::text[]),
  (39, 'syd', 'Caterpillar', '140', 'grader', 2017, 3726, 'CAT014085012', array['level1']::text[]),
  (40, 'syd', 'Hamm', 'H 13i', 'roller', 2014, 9168, 'HAMH13I57985', array['scrapped']::text[]),
  (41, 'syd', 'Volvo', 'EC220E', 'excavator_tracked', 2023, 1707, 'VCEEC220E95646', '{}'::text[]),
  (42, 'syd', 'Ponsse', 'Ergo', 'forestry_harvester', 2013, 12220, 'PONERGO67542', '{}'::text[]),
  (43, 'syd', 'Vögele', 'Super 1800-3i', 'paver', 2020, 5538, 'VGLSUPER184748', '{}'::text[]),
  (44, 'syd', 'Manitou', 'MT1840', 'telehandler', 2017, 9720, 'MANMT184021032', array['stock']::text[]),
  (45, 'syd', 'John Deere', '1270G', 'forestry_harvester', 2024, 1686, '1YJ1270G71697', array['level2']::text[]),
  (46, 'norr', 'John Deere', '1270G', 'forestry_harvester', 2017, 7200, '1YJ1270G79504', array['level1']::text[]),
  (47, 'norr', 'John Deere', '1270G', 'forestry_harvester', 2017, 5526, '1YJ1270G15662', '{}'::text[]),
  (48, 'norr', 'Ponsse', 'Ergo', 'forestry_harvester', 2015, 9680, 'PONERGO08592', '{}'::text[]),
  (49, 'norr', 'John Deere', '1270G', 'forestry_harvester', 2023, 2391, '1YJ1270G12226', '{}'::text[]),
  (50, 'norr', 'John Deere', '1270G', 'forestry_harvester', 2024, 856, '1YJ1270G70822', '{}'::text[]),
  (51, 'norr', 'Ponsse', 'Ergo', 'forestry_harvester', 2019, 6034, 'PONERGO87474', '{}'::text[]),
  (52, 'norr', 'Ponsse', 'Ergo', 'forestry_harvester', 2020, 5526, 'PONERGO35741', '{}'::text[]),
  (53, 'norr', 'Ponsse', 'Buffalo', 'forestry_forwarder', 2020, 6438, 'PONBUFFAL28760', '{}'::text[]),
  (54, 'berg-draft', 'Manitou', 'MT1840', 'telehandler', 2016, 7080, 'MANMT184094447', '{}'::text[]),
  (55, 'berg-draft', 'Atlas Copco', 'XAS 188', 'compressor', 2020, 4572, 'ACXXAS18858422', '{}'::text[]),
  (56, 'berg-draft', 'JCB', '3CX', 'backhoe', 2015, 4015, 'JCB3CX33493', '{}'::text[]),
  (57, 'nordmaskin-draft', 'Metso', 'Lokotrack LT106', 'crusher', 2021, 4335, 'METLOKOTR03757', '{}'::text[]),
  (58, 'nordmaskin-draft', 'Volvo', 'EW160E', 'excavator_wheeled', 2015, 3377, 'VCEEW160E78128', '{}'::text[]),
  (59, 'berg-dup', 'Volvo', 'L120H', 'wheel_loader', 2022, 1440, 'VCEL120H93778', array['duplicate_of:7']::text[]),
  (60, 'syd-extra', 'Volvo', 'EW160E', 'excavator_wheeled', 2012, 8932, 'VCEEW160E09834', '{}'::text[]);

create or replace function seed.owner(p_key text) returns table (org_id uuid, email text) language sql as $$
  select seed.org(x.slug), x.email from (values
    ('berg', 'bergs-schakt-entreprenad-ab', 'berg@demo.se'), ('lena', 'lena-gravmaskin', 'lena@demo.se'),
    ('kommun', 'kommunfastigheter-vast', 'kommun@demo.se'), ('nordmaskin', 'nordmaskin-ab', 'nordmaskin@demo.se'),
    ('syd', 'entreprenadcenter-syd-ab', 'syd@demo.se'), ('norr', 'skogsmaskiner-norr-ab', 'norr@demo.se'),
    ('bank', 'demo-bank-finans', 'bank@demo.se'), ('finans', 'nordisk-maskinfinans', 'finans@demo.se'))
    x(key, slug, email) where x.key = p_key
$$;

do $$
declare
  p record; own record; r jsonb; mid uuid; t text; fin record; d jsonb; typ text; params jsonb; sig uuid;
  op uuid := seed.org('maskinid'); insp uuid := seed.org('maskinkontroll-sverige-ab'); nord uuid := seed.org('nordmaskin-ab');
  b1 jsonb; b2 jsonb; b3 jsonb; code text; lbl_org uuid; lbl_email text; bound int := 0;
begin
  -- Label batches: 200 labels (SPEC §17)
  perform seed.act('admin@demo.se');
  b1 := public.print_label_batch(null, 100, nord, 'Tryckeri Demo 1');
  b2 := public.print_label_batch(null, 50, null, 'Tryckeri Demo 2');
  b3 := public.print_label_batch(null, 50, seed.org('entreprenadcenter-syd-ab'), 'Tryckeri Demo 3');

  for p in select * from seed.machine_plan order by slot loop
    select * into own from seed.owner(case split_part(p.plan, '-', 1) when 'berg' then case when p.plan = 'berg-dup' then 'kommun' else 'berg' end else split_part(p.plan, '-', 1) end);
    d := jsonb_build_object('make', p.make, 'model', p.model, 'year', p.year, 'category', p.category, 'hour_meter', p.hours,
      'identifiers', jsonb_build_array(jsonb_build_object('type', 'serial', 'value',
        case when p.scenarios @> array['duplicate_of:7'] then (select serial from seed.machine_plan where slot = 7) else p.serial end)),
      'model_id', (select id from public.machine_models mm where mm.make = case when p.make = 'Engcon' then 'Tiltrotator' else p.make end and mm.model = case when p.make = 'Engcon' then 'Engcon EC219' else p.model end));
    if p.plan like '%-draft' then
      perform seed.act(own.email);
      perform public.save_machine_draft(own.org_id, d || jsonb_build_object('step', 2));
      continue;
    end if;
    if 'new_sale' = any (p.scenarios) then
      perform seed.act('nordmaskin@demo.se');
      r := app.create_machine(nord, d || jsonb_build_object('owner_org_id', own.org_id, 'first_sale_date', (current_date - 20)::text), 'new_sale', null, 2::smallint, 'new_sale');
    else
      perform seed.act(own.email);
      r := public.register_machine(own.org_id, d);
    end if;
    mid := (r ->> 'id')::uuid;
    insert into seed.machine_ids values (p.slot, mid) on conflict do nothing;

    -- Label
    if bound < 55 and (r ->> 'status') in ('active', 'disputed') then
      lbl_org := case when own.org_id = nord then nord when own.org_id = seed.org('entreprenadcenter-syd-ab') then own.org_id else null end;
      select l.code into code from public.labels l where l.status in ('printed', 'assigned') and l.machine_id is null
        and l.assigned_org_id is not distinct from lbl_org order by l.created_at, l.code limit 1;
      if code is not null then
        perform seed.act(own.email);
        perform public.bind_label(own.org_id, mid, code, 'primary');
        bound := bound + 1;
      end if;
    end if;

    -- Verification levels
    if 'level2' = any (p.scenarios) then
      perform seed.act('kontroll@demo.se');
      perform app.apply_verification(mid, 2, 'physical', insp, '{"seed":true}');
    elsif 'level1' = any (p.scenarios) then
      perform seed.act('verifier@demo.se');
      perform app.apply_verification(mid, 1, 'documents', op, '{"seed":true}');
    end if;

    -- Encumbrances
    foreach t in array p.scenarios loop
      if t like 'enc:%' then
        select * into fin from seed.owner(split_part(t, ':', 2));
        typ := split_part(t, ':', 3);
        perform seed.act(fin.email);
        params := jsonb_build_object('type', typ, 'contract_ref', 'AVT-' || p.slot || '-' || upper(left(split_part(t, ':', 2), 3)),
          'start_date', (current_date - 25)::text, 'end_date', (current_date + 900)::text);
        sig := seed.sign(fin.org_id, 'register_encumbrance', mid, params);
        perform public.register_encumbrance(fin.org_id, mid, typ::public.encumbrance_type, params ->> 'contract_ref',
          (params ->> 'start_date')::date, (params ->> 'end_date')::date, null, null, sig);
      end if;
    end loop;

    if 'stolen' = any (p.scenarios) then
      perform seed.act(own.email);
      sig := seed.sign(own.org_id, 'raise_flag_stolen', mid, jsonb_build_object('reference', '5000-K' || (1200 + p.slot) || '-26'));
      perform public.raise_flag(own.org_id, mid, 'stolen', '5000-K' || (1200 + p.slot) || '-26',
        'Stulen från arbetsplats under natten.', now() - interval '6 days', 'Västerås, Finnslätten', sig);
    end if;
    if 'blocked' = any (p.scenarios) then
      perform seed.act('polisen@demo.se');
      perform public.raise_flag(seed.org('polisen-demo'), mid, 'under_investigation', 'PM-2026-4411', 'Utreds i ärende om misstänkt häleri.');
    end if;
    if 'scrapped' = any (p.scenarios) then
      perform seed.act(own.email);
      sig := seed.sign(own.org_id, 'deregister_machine', mid, '{"reason":"scrapped","label_disposition":"destroyed"}');
      perform public.deregister_machine(own.org_id, mid, 'scrapped', 'destroyed', sig, 'Skrotad hos godkänd skrotfirma');
    end if;
    if 'transfer' = any (p.scenarios) then
      perform seed.act(own.email);
      perform public.initiate_transfer(own.org_id, mid, current_date - 2, seed.org('kommunfastigheter-vast'));
    end if;
  end loop;

  -- Dealer machines: only the tagged ones are for sale (6 in stock, SPEC §17); the rest are rental/own fleet.
  update public.machines m set stock_status = case when mp.scenarios @> array['stock'] then 'stock' else null end
  from seed.machine_plan mp join seed.machine_ids i on i.slot = mp.slot
  where m.id = i.machine_id and m.owner_org_id in (seed.org('nordmaskin-ab'), seed.org('entreprenadcenter-syd-ab'), seed.org('skogsmaskiner-norr-ab'));

  -- Three secondary (hidden) labels on physically verified machines ⇒ 55 bound labels in total.
  for p in select i.machine_id, ow.email, ow.org_id from seed.machine_plan mp join seed.machine_ids i on i.slot = mp.slot
             cross join lateral seed.owner(split_part(mp.plan, '-', 1)) ow
           where mp.scenarios @> array['level2'] and ow.org_id not in (nord, seed.org('entreprenadcenter-syd-ab'))
           order by mp.slot limit 3 loop
    select l.code into code from public.labels l where l.status = 'printed' and l.assigned_org_id is null order by l.created_at, l.code limit 1;
    perform seed.act(p.email);
    perform public.bind_label(p.org_id, p.machine_id, code, 'secondary');
  end loop;
end $$;
