-- =====================================================================
-- 0007 documents, access log, share links, rate limiting
-- (SPEC §4.5, §5.3, §6.10, §11.3, §11.5, §16 points 2, 10, 11)
-- =====================================================================

-- ---------- Documents ----------
create table public.documents (
  id                  uuid primary key default gen_random_uuid(),
  machine_id          uuid references public.machines (id),
  org_id              uuid not null references public.organizations (id),
  type                public.document_type not null,
  storage_path        text not null unique,
  filename            text not null,
  mime                text not null check (mime in ('application/pdf', 'image/jpeg', 'image/png', 'image/heic')),
  size_bytes          bigint not null check (size_bytes between 1 and 26214400),  -- max 25 MB
  sha256              text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  uploaded_by_user_id uuid,
  visibility          public.document_visibility not null default 'owner',
  status              text not null default 'pending_upload' check (status in ('pending_upload', 'scanning', 'clean', 'infected', 'failed')),
  exif_stripped       boolean not null default false,
  gps_consent_location jsonb,                -- only with explicit consent (theft scans), never from EXIF
  generated           boolean not null default false,   -- PDFs generated by the system (certificates, receipts, reports)
  archived_at         timestamptz,
  created_at          timestamptz not null default now()
);
create index documents_machine_idx on public.documents (machine_id, created_at desc);
create index documents_org_idx on public.documents (org_id);

-- Storage buckets: private documents (signed URLs, 5 min, issued by Edge Function document-url) and public machine
-- photos (only the primary photo, EXIF stripped, copied there by av-scan).
do $$ begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('documents', 'documents', false, 26214400, array['application/pdf', 'image/jpeg', 'image/png', 'image/heic'])
    on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('machine-photos', 'machine-photos', true, 5242880, array['image/jpeg', 'image/png'])
    on conflict (id) do update set public = true;
  end if;
end $$;

-- Uploads go straight to storage, but only to a path reserved by create_document_upload for this user.
create or replace function app.can_upload_document(p_path text)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.documents d where d.storage_path = p_path
    and d.uploaded_by_user_id = auth.uid() and d.status = 'pending_upload')
$$;
grant execute on function app.can_upload_document(text) to authenticated;
do $$ begin
  if to_regclass('storage.objects') is not null then
    execute $p$
      create policy documents_upload_reserved on storage.objects for insert to authenticated with check (
        bucket_id = 'documents' and app.can_upload_document(name))
    $p$;
  end if;
end $$;

-- ---------- Access log (partitioned by month, SPEC §15) ----------
create table public.access_log (
  id                uuid not null default gen_random_uuid(),
  machine_id        uuid not null,
  viewer_user_id    uuid,
  viewer_org_id     uuid,
  viewer_type       public.viewer_type not null,
  via               public.access_via not null,
  purpose           text,
  ip_hash           text,
  approx_location   jsonb,
  user_agent_family text,
  visible_to_owner  boolean not null default true,
  created_at        timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.access_log_default partition of public.access_log default;
alter table public.access_log_default enable row level security;
revoke all on public.access_log_default from public, anon, authenticated;
create index access_log_machine_idx on public.access_log (machine_id, created_at desc);
create index access_log_viewer_org_idx on public.access_log (viewer_org_id, created_at desc);

-- Creates the monthly partitions for the current and next p_months months (run by the jobs runner).
create or replace function app.ensure_monthly_partitions(p_table text, p_months int default 3)
returns int language plpgsql security definer set search_path = '' as $$
declare i int; start_ date; end_ date; name_ text; n int := 0;
begin
  for i in 0..p_months loop
    start_ := (date_trunc('month', now()) + make_interval(months => i))::date;
    end_ := (start_ + interval '1 month')::date;
    name_ := p_table || '_' || to_char(start_, 'YYYYMM');
    if to_regclass('public.' || name_) is null then
      -- Rows already in the default partition for that range must move first.
      execute format('create table public.%I (like public.%I including defaults)', name_ || '_tmp', p_table);
      execute format('with moved as (delete from public.%I where created_at >= %L and created_at < %L returning *) insert into public.%I select * from moved',
        p_table || '_default', start_, end_, name_ || '_tmp');
      execute format('alter table public.%I attach partition public.%I for values from (%L) to (%L)', p_table, name_ || '_tmp', start_, end_);
      execute format('alter table public.%I rename to %I', name_ || '_tmp', name_);
      -- Partitions are tables of their own: without RLS a direct select would bypass the parent's policies.
      execute format('alter table public.%I enable row level security', name_);
      execute format('revoke all on public.%I from public, anon, authenticated', name_);
      n := n + 1;
    end if;
  end loop;
  return n;
end $$;
select app.ensure_monthly_partitions('access_log', 2);

-- ---------- Share links ----------
create table public.share_links (
  id                 uuid primary key default gen_random_uuid(),
  machine_id         uuid references public.machines (id),
  org_id             uuid not null references public.organizations (id),
  created_by_user_id uuid,
  token_hash         text not null unique,
  token_prefix       text not null,
  scope              public.share_scope not null,
  params             jsonb not null default '{}'::jsonb,    -- e.g. {project_id} for fleet reports
  expires_at         timestamptz not null,
  max_views          int check (max_views is null or max_views > 0),
  views              int not null default 0,
  revoked_at         timestamptz,
  created_at         timestamptz not null default now()
);
create index share_links_machine_idx on public.share_links (machine_id);
create index share_links_org_idx on public.share_links (org_id);

-- ---------- Rate limiting (SPEC §11.3: 30/min, 300/day per IP on public lookups) ----------
create table app.rate_limits (
  key          text not null,
  window_start timestamptz not null,
  hits         int not null default 0,
  primary key (key, window_start)
);
revoke all on app.rate_limits from public, anon, authenticated, service_role;

-- Counts a hit; returns false when the limit for the window is exceeded.
create or replace function app.rate_limit_hit(p_key text, p_limit int, p_window interval)
returns boolean language plpgsql security definer set search_path = '' as $$
declare ws timestamptz := to_timestamp(floor(extract(epoch from now()) / extract(epoch from p_window)) * extract(epoch from p_window));
  n int;
begin
  insert into app.rate_limits (key, window_start, hits) values (p_key, ws, 1)
  on conflict (key, window_start) do update set hits = app.rate_limits.hits + 1
  returning hits into n;
  return n <= p_limit;
end $$;

-- ---------- Access logging ----------
create or replace function app.viewer_type_for(p_org_id uuid)
returns public.viewer_type language sql stable security definer set search_path = '' as $$
  select case
    when p_org_id is null then 'public'
    when app.is_operator() then 'operator'
    when app.has_org_type(p_org_id, 'authority') then 'authority'
    when app.has_org_type(p_org_id, 'financier') then 'financier'
    when app.has_org_type(p_org_id, 'insurer') then 'insurer'
    when app.has_org_type(p_org_id, 'inspector') then 'inspector'
    when app.has_org_type(p_org_id, 'dealer') then 'dealer'
    when app.has_org_type(p_org_id, 'marketplace') then 'marketplace'
    when app.has_org_type(p_org_id, 'manufacturer') then 'manufacturer'
    when app.has_org_type(p_org_id, 'client') then 'client'
    else 'owner' end::public.viewer_type
$$;

-- Logs every read of another organisation's machine (SPEC §0 principle 3). Authority reads are hidden from the owner
-- unless the authority org's setting show_authority_reads_to_owner is true; operator reads are never shown.
create or replace function app.after_lookup(p_org_id uuid, p_machine_ids uuid[], p_via text)
returns void language plpgsql security definer set search_path = '' as $$
declare mid uuid; m public.machines; vt public.viewer_type; visible boolean;
begin
  vt := case when app.current_api_key_id() is not null then 'api' else app.viewer_type_for(p_org_id) end;
  visible := case
    when vt = 'operator' then false
    when vt = 'authority' then coalesce((select (settings ->> 'show_authority_reads_to_owner')::boolean from public.organizations where id = p_org_id), false)
    else true end;
  foreach mid in array coalesce(p_machine_ids, '{}') loop
    select * into m from public.machines where id = mid;
    if m.id is null or m.owner_org_id = p_org_id or m.user_org_id = p_org_id then continue; end if;
    -- One row per viewer org and machine per hour for plain web views, every row for checks and scans.
    if p_via = 'web' and exists (select 1 from public.access_log a where a.machine_id = mid and a.viewer_org_id is not distinct from p_org_id
        and a.viewer_user_id is not distinct from auth.uid() and a.via = 'web' and a.created_at > now() - interval '1 hour') then
      continue;
    end if;
    insert into public.access_log (machine_id, viewer_user_id, viewer_org_id, viewer_type, via, visible_to_owner)
    values (mid, auth.uid(), p_org_id, vt, p_via::public.access_via, visible);
  end loop;
end $$;

-- Public scan through Edge Function scan-log (service role): rate limit, card, access log, stolen-machine alerts.
create or replace function public.log_public_scan(p_code text, p_reg text, p_ip_hash text, p_user_agent_family text default null,
  p_location jsonb default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare card jsonb; m public.machines; loc jsonb; ev public.events;
begin
  if not app.rate_limit_hit('scan:min:' || coalesce(p_ip_hash, 'none'), app.config_text('PUBLIC_RATE_PER_MIN', '30')::int, interval '1 minute')
     or not app.rate_limit_hit('scan:day:' || coalesce(p_ip_hash, 'none'), app.config_text('PUBLIC_RATE_PER_DAY', '300')::int, interval '1 day') then
    perform app.raise('RATE_LIMITED');
  end if;
  card := public.public_machine_card(p_code, p_reg);
  if not (card ->> 'found')::boolean then return card; end if;
  select * into m from public.machines where reg_number = card -> 'card' ->> 'reg_number';
  -- Location only with the scanner's consent, rounded to ~1 km.
  loc := case when p_location ? 'lat' and p_location ? 'lng' then jsonb_build_object('lat', round((p_location ->> 'lat')::numeric, 2),
    'lng', round((p_location ->> 'lng')::numeric, 2), 'city', p_location ->> 'city') when p_location ? 'city' then jsonb_build_object('city', p_location ->> 'city') end;
  insert into public.access_log (machine_id, viewer_type, via, ip_hash, approx_location, user_agent_family)
  values (m.id, 'public', case when p_code is not null then 'scan' else 'web' end::public.access_via, p_ip_hash, loc, left(p_user_agent_family, 40));
  if m.status = 'stolen' then
    ev := app.log_event('machine.stolen_scanned', m.id, m.owner_org_id, null, jsonb_build_object('location', loc, 'via', case when p_code is not null then 'scan' else 'web' end));
    perform app.notify_org(m.owner_org_id, 'machine.stolen_scanned',
      jsonb_build_object('machine_id', m.id, 'reg_number', m.reg_number, 'location', loc, 'at', app.iso_ts(now())), '/machines/' || m.id, 'critical');
    perform app.notify_org(f.raised_by_org_id, 'machine.stolen_scanned',
      jsonb_build_object('machine_id', m.id, 'reg_number', m.reg_number, 'location', loc, 'at', app.iso_ts(now())), '/machines/' || m.id, 'critical')
      from public.flags f where f.machine_id = m.id and f.status = 'active' and f.type = 'stolen' and f.raised_by_org_id <> m.owner_org_id;
    perform app.enqueue_webhook(m.owner_org_id, 'machine.scanned', m.id, jsonb_build_object('location', loc), ev.id);
    perform app.enqueue_webhook(e.holder_org_id, 'machine.scanned', m.id, jsonb_build_object('location', loc), ev.id)
      from public.encumbrances e where e.machine_id = m.id and e.status = 'active';
  end if;
  return card;
end $$;

-- "Jag har sett maskinen" on the red page: a sighting with consented location and optional contact (SPEC §5.3).
create or replace function public.report_sighting(p_code text, p_reg text, p_ip_hash text, p_location jsonb, p_message text default null,
  p_contact text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare card jsonb; m public.machines;
begin
  if not app.rate_limit_hit('sighting:' || coalesce(p_ip_hash, 'none'), 5, interval '1 hour') then perform app.raise('RATE_LIMITED'); end if;
  card := public.public_machine_card(p_code, p_reg);
  if not (card ->> 'found')::boolean then perform app.raise('NOT_FOUND'); end if;
  select * into m from public.machines where reg_number = card -> 'card' ->> 'reg_number';
  if m.status <> 'stolen' then return jsonb_build_object('ok', true); end if;
  perform app.log_event('machine.sighting_reported', m.id, m.owner_org_id, null,
    jsonb_build_object('location', p_location, 'has_contact', p_contact is not null));
  perform app.notify_org(m.owner_org_id, 'machine.sighting_reported', jsonb_build_object('machine_id', m.id, 'reg_number', m.reg_number,
    'location', p_location, 'message', left(p_message, 1000), 'contact', left(p_contact, 200)), '/machines/' || m.id, 'critical');
  perform app.notify_org(f.raised_by_org_id, 'machine.sighting_reported', jsonb_build_object('machine_id', m.id, 'reg_number', m.reg_number,
    'location', p_location, 'message', left(p_message, 1000), 'contact', left(p_contact, 200)), '/machines/' || m.id, 'critical')
    from public.flags f where f.machine_id = m.id and f.status = 'active' and f.type = 'stolen' and f.raised_by_org_id <> m.owner_org_id;
  return jsonb_build_object('ok', true);
end $$;

-- Signed-in scan of a label: full role view + access log with via=scan.
create or replace function public.scan_label(p_org_id uuid, p_code text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id, 'readonly', false); l public.labels; v jsonb;
begin
  select * into l from public.labels where code = p_code;
  if l.id is null or l.machine_id is null then return jsonb_build_object('found', false); end if;
  perform app.after_lookup(actor, array[l.machine_id], 'scan');
  v := app.machine_view(l.machine_id, actor);
  if v is null then return jsonb_build_object('found', false); end if;
  return jsonb_build_object('found', true, 'label_status', l.status, 'machine', v);
end $$;

create or replace function public.list_access_log(p_org_id uuid, p_machine_id uuid, p_limit int default 200)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id, 'readonly', false); rel text[] := app.machine_relations(p_machine_id, array[actor]);
  full_log boolean := app.is_operator() or app.has_org_type(actor, 'authority');
begin
  if not (rel && array['owner', 'user'] or full_log) then perform app.raise('FORBIDDEN'); end if;
  return coalesce((select jsonb_agg(jsonb_build_object('id', a.id, 'viewer_type', a.viewer_type, 'via', a.via, 'created_at', a.created_at,
      'viewer_org_name', case when a.viewer_type in ('public', 'api') and a.viewer_org_id is null then null
        else (select name from public.organizations where id = a.viewer_org_id) end,
      'approx_location', a.approx_location, 'user_agent_family', a.user_agent_family,
      'ip_hash', case when full_log then a.ip_hash end) order by a.created_at desc)
    from (select * from public.access_log where machine_id = p_machine_id and (full_log or visible_to_owner)
          order by created_at desc limit least(greatest(p_limit, 1), 1000)) a), '[]'::jsonb);
end $$;

-- ---------- Documents RPC ----------
-- Who may read a document (SPEC §11.2 documents row).
create or replace function app.can_read_document(d public.documents)
returns boolean language plpgsql stable security definer set search_path = '' as $$
declare rel text[];
begin
  if d.id is null or d.status not in ('clean', 'scanning') then return false; end if;
  if d.org_id = any (app.current_org_ids()) or app.is_operator() or app.acts_as('authority') then return true; end if;
  if d.machine_id is null then return false; end if;
  if d.visibility = 'public' then return true; end if;
  rel := app.machine_relations(d.machine_id);
  if rel && array['owner', 'user'] then
    -- Documents follow the machine to the new owner unless the uploader kept them private (visibility owner and not
    -- chosen to follow at transfer).
    return d.visibility <> 'owner' or d.org_id = any (app.current_org_ids())
      or exists (select 1 from public.transfers t where t.machine_id = d.machine_id and t.status = 'completed'
                 and d.id = any (t.document_ids) and t.to_org_id = any (app.current_org_ids()))
      or not exists (select 1 from public.transfers t where t.machine_id = d.machine_id and t.status = 'completed' and t.completed_at > d.created_at);
  end if;
  if 'holder' = any (rel) and d.visibility in ('owner_and_financier', 'verifiers') then return true; end if;
  if 'inspector_assigned' = any (rel) and d.visibility = 'verifiers' then return true; end if;
  return false;
end $$;

create or replace function app.document_json(d public.documents)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('id', d.id, 'machine_id', d.machine_id, 'type', d.type, 'filename', d.filename, 'mime', d.mime,
    'size_bytes', d.size_bytes, 'sha256', d.sha256, 'visibility', d.visibility, 'status', d.status, 'generated', d.generated,
    'uploaded_by', (select name from public.organizations where id = d.org_id), 'org_id', d.org_id, 'created_at', d.created_at)
$$;

create or replace function public.create_document_upload(p_org_id uuid, p_machine_id uuid, p_type public.document_type, p_filename text,
  p_mime text, p_size_bytes bigint, p_sha256 text, p_visibility public.document_visibility default 'owner')
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); d public.documents; rel text[]; fname text;
begin
  if p_machine_id is not null then
    rel := app.machine_relations(p_machine_id, array[actor]);
    if not (rel && array['owner', 'user', 'registered_by', 'draft_owner', 'holder', 'inspector_assigned', 'transfer_party', 'operator']
            or app.has_org_type(actor, 'inspector') or app.has_org_type(actor, 'dealer')) then
      perform app.raise('FORBIDDEN');
    end if;
  end if;
  if p_mime not in ('application/pdf', 'image/jpeg', 'image/png', 'image/heic') then perform app.raise('VALIDATION', '{"field":"mime"}'); end if;
  if p_size_bytes is null or p_size_bytes < 1 or p_size_bytes > 26214400 then perform app.raise('VALIDATION', '{"field":"size","max":26214400}'); end if;
  if p_sha256 !~ '^[0-9a-f]{64}$' then perform app.raise('VALIDATION', '{"field":"sha256"}'); end if;
  fname := left(regexp_replace(coalesce(p_filename, 'file'), '[^A-Za-z0-9._-]+', '_', 'g'), 120);
  insert into public.documents (machine_id, org_id, type, storage_path, filename, mime, size_bytes, sha256, uploaded_by_user_id, visibility)
  values (p_machine_id, actor, p_type, actor || '/' || gen_random_uuid() || '/' || fname, fname, p_mime, p_size_bytes, p_sha256, auth.uid(), p_visibility)
  returning * into d;
  return jsonb_build_object('id', d.id, 'bucket', 'documents', 'path', d.storage_path);
end $$;

-- After the upload: the event carries the sha256 (SPEC §11.5). av-scan then marks the file clean/infected.
create or replace function public.finalize_document(p_org_id uuid, p_document_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); d public.documents; owner_org uuid;
begin
  select * into d from public.documents where id = p_document_id and org_id = actor and status = 'pending_upload' for update;
  if d.id is null then perform app.raise('NOT_FOUND'); end if;
  if to_regclass('storage.objects') is not null and not app.is_demo_mode() then
    if not exists (select 1 from storage.objects o where o.bucket_id = 'documents' and o.name = d.storage_path) then
      perform app.raise('UPLOAD_MISSING');
    end if;
  end if;
  update public.documents set status = case when app.is_demo_mode() then 'clean' else 'scanning' end,
    exif_stripped = d.mime not in ('image/jpeg', 'image/heic') or app.is_demo_mode()
  where id = d.id returning * into d;
  select owner_org_id into owner_org from public.machines where id = d.machine_id;
  perform app.log_event('document.uploaded', d.machine_id, coalesce(owner_org, actor), actor,
    jsonb_build_object('document_id', d.id, 'type', d.type, 'sha256', d.sha256, 'size_bytes', d.size_bytes, 'visibility', d.visibility));
  return app.document_json(d);
end $$;

-- Result from Edge Function av-scan (service role).
create or replace function public.record_document_scan(p_document_id uuid, p_clean boolean, p_exif_stripped boolean, p_sha256_after text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare d public.documents;
begin
  update public.documents set status = case when p_clean then 'clean' else 'infected' end, exif_stripped = p_exif_stripped
  where id = p_document_id returning * into d;
  if d.id is null then perform app.raise('NOT_FOUND'); end if;
  if not p_clean then
    perform app.log_event('document.quarantined', d.machine_id, d.org_id, null, jsonb_build_object('document_id', d.id));
    perform app.notify_org(d.org_id, 'document.infected', jsonb_build_object('filename', d.filename), '/machines/' || d.machine_id, 'warning');
  elsif p_sha256_after is not null and p_sha256_after <> d.sha256 then
    perform app.log_event('document.sanitized', d.machine_id, d.org_id, null,
      jsonb_build_object('document_id', d.id, 'sha256_original', d.sha256, 'sha256_stored', p_sha256_after));
  end if;
  return app.document_json(d);
end $$;

create or replace function public.list_documents(p_org_id uuid, p_machine_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id, 'readonly', false);
begin
  return coalesce((select jsonb_agg(app.document_json(d) order by d.created_at desc) from public.documents d
    where d.machine_id = p_machine_id and d.archived_at is null and app.can_read_document(d)), '[]'::jsonb);
end $$;

-- Authorises a download; Edge Function document-url then signs a 5-minute URL.
create or replace function public.authorize_document_download(p_document_id uuid, p_share_token text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare d public.documents; s public.share_links;
begin
  select * into d from public.documents where id = p_document_id and archived_at is null;
  if d.id is null then perform app.raise('NOT_FOUND'); end if;
  if p_share_token is not null then
    select * into s from public.share_links where token_hash = app.sha256_hex(p_share_token) and revoked_at is null and expires_at > now();
    if s.id is null or s.machine_id is distinct from d.machine_id or d.visibility not in ('verifiers', 'public') or d.status <> 'clean' then
      perform app.raise('NOT_FOUND');
    end if;
  elsif not app.can_read_document(d) or d.status <> 'clean' then
    perform app.raise('NOT_FOUND');
  end if;
  if d.machine_id is not null then
    perform app.after_lookup((select x from unnest(app.current_org_ids()) x limit 1), array[d.machine_id], case when p_share_token is null then 'web' else 'share_link' end);
  end if;
  return jsonb_build_object('bucket', 'documents', 'path', d.storage_path, 'filename', d.filename, 'mime', d.mime, 'expires_in', 300);
end $$;

create or replace function public.set_document_visibility(p_org_id uuid, p_document_id uuid, p_visibility public.document_visibility)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); d public.documents;
begin
  select * into d from public.documents where id = p_document_id for update;
  if d.id is null then perform app.raise('NOT_FOUND'); end if;
  if (d.org_id = actor or (select owner_org_id from public.machines where id = d.machine_id) = actor) is not true then perform app.raise('FORBIDDEN'); end if;
  if d.type in ('police_report', 'financing_contract') and p_visibility = 'public' then perform app.raise('VALIDATION', '{"field":"visibility"}'); end if;
  update public.documents set visibility = p_visibility where id = d.id returning * into d;
  perform app.log_event('document.visibility_changed', d.machine_id, d.org_id, actor, jsonb_build_object('document_id', d.id, 'visibility', p_visibility));
  return app.document_json(d);
end $$;

create or replace function public.archive_document(p_org_id uuid, p_document_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); d public.documents;
begin
  update public.documents set archived_at = now() where id = p_document_id and org_id = actor and archived_at is null and not generated
  returning * into d;
  if d.id is null then perform app.raise('NOT_FOUND'); end if;
  perform app.log_event('document.archived', d.machine_id, d.org_id, actor, jsonb_build_object('document_id', d.id, 'sha256', d.sha256));
  return jsonb_build_object('ok', true);
end $$;

-- Primary photo: a clean, public photo_machine document; av-scan copies it to the public machine-photos bucket.
create or replace function public.set_primary_photo(p_org_id uuid, p_machine_id uuid, p_document_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); d public.documents; m public.machines;
begin
  select * into m from public.machines where id = p_machine_id;
  if (m.owner_org_id = actor or m.registered_by_org_id = actor and m.status = 'draft') is not true then perform app.raise('FORBIDDEN'); end if;
  select * into d from public.documents where id = p_document_id and machine_id = p_machine_id;
  if d.id is null or d.type <> 'photo_machine' or d.mime not in ('image/jpeg', 'image/png') then perform app.raise('VALIDATION', '{"field":"document"}'); end if;
  update public.documents set visibility = 'public' where id = d.id;
  update public.machines set primary_photo_path = m.id || '/' || d.id || case when d.mime = 'image/png' then '.png' else '.jpg' end where id = m.id;
  perform app.log_event('machine.photo_set', m.id, m.owner_org_id, actor, jsonb_build_object('document_id', d.id, 'sha256', d.sha256));
  return jsonb_build_object('ok', true, 'primary_photo_path', m.id || '/' || d.id || case when d.mime = 'image/png' then '.png' else '.jpg' end,
    'source_path', d.storage_path);
end $$;

-- ---------- Share links (SPEC §6.10) ----------
create or replace function public.create_share_link(p_org_id uuid, p_machine_id uuid, p_scope public.share_scope default 'buyer_report',
  p_days int default 7, p_max_views int default null, p_params jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); token text := encode(extensions.gen_random_bytes(24), 'hex'); s public.share_links;
begin
  if p_days not in (1, 7, 30, 90) then perform app.raise('VALIDATION', '{"field":"days"}'); end if;
  if p_scope in ('public_card', 'buyer_report') then
    if p_machine_id is null or (select owner_org_id from public.machines where id = p_machine_id) is distinct from actor then
      perform app.raise('FORBIDDEN');
    end if;
  elsif p_machine_id is not null then
    perform app.raise('VALIDATION', '{"field":"machine_id"}');
  end if;
  insert into public.share_links (machine_id, org_id, created_by_user_id, token_hash, token_prefix, scope, params, expires_at, max_views)
  values (p_machine_id, actor, auth.uid(), app.sha256_hex(token), left(token, 8), p_scope, coalesce(p_params, '{}'),
          now() + make_interval(days => p_days), p_max_views)
  returning * into s;
  perform app.log_event('share_link.created', p_machine_id, actor, actor,
    jsonb_build_object('share_link_id', s.id, 'scope', p_scope, 'expires_at', s.expires_at, 'max_views', p_max_views));
  return jsonb_build_object('id', s.id, 'token', token, 'expires_at', s.expires_at, 'scope', s.scope, 'max_views', s.max_views);
end $$;

create or replace function public.list_share_links(p_org_id uuid, p_machine_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id, 'readonly', false);
begin
  return coalesce((select jsonb_agg(jsonb_build_object('id', s.id, 'machine_id', s.machine_id, 'scope', s.scope, 'token_prefix', s.token_prefix,
      'expires_at', s.expires_at, 'max_views', s.max_views, 'views', s.views, 'revoked_at', s.revoked_at, 'created_at', s.created_at,
      'active', s.revoked_at is null and s.expires_at > now() and (s.max_views is null or s.views < s.max_views)) order by s.created_at desc)
    from public.share_links s where s.org_id = actor and (p_machine_id is null or s.machine_id = p_machine_id)), '[]'::jsonb);
end $$;

create or replace function public.revoke_share_link(p_org_id uuid, p_share_link_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := app.require_actor(p_org_id); s public.share_links;
begin
  update public.share_links set revoked_at = now() where id = p_share_link_id and org_id = actor and revoked_at is null returning * into s;
  if s.id is null then perform app.raise('NOT_FOUND'); end if;
  perform app.log_event('share_link.revoked', s.machine_id, actor, actor, jsonb_build_object('share_link_id', s.id));
  return jsonb_build_object('ok', true);
end $$;

-- Buyer report content (SPEC §6.10): history, verifications, financing yes/no + holder name, documents with visibility
-- ≥ verifiers, hours, service. Later steps extend it via app.buyer_report_extras.
create or replace function app.buyer_report_extras(p_machine_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$ select '{}'::jsonb $$;

create or replace function app.buyer_report(p_machine_id uuid)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare m public.machines; af public.encumbrances;
begin
  select * into m from public.machines where id = p_machine_id;
  af := app.active_financing(m.id);
  return app.machine_base_json(m) || jsonb_build_object(
    'owner_ordinal', (select count(*) from public.ownerships where machine_id = m.id),
    'serial_masked', app.mask_serial(app.machine_primary_serial(m.id)),
    'financing', jsonb_build_object('has_active', af.id is not null,
      'holder', case when af.id is not null then (select name from public.organizations where id = af.holder_org_id) end,
      'type', af.type),
    'flags', coalesce((select jsonb_agg(jsonb_build_object('type', type, 'raised_at', raised_at)) from public.flags where machine_id = m.id and status = 'active'), '[]'::jsonb),
    'history', coalesce((select jsonb_agg(jsonb_build_object('type', e.type, 'created_at', e.created_at,
        'actor_org', (select name from public.organizations where id = e.actor_org_id)) order by e.seq desc)
      from public.events e where e.machine_id = m.id and e.type not in ('machine.checked', 'document.visibility_changed', 'share_link.created', 'share_link.revoked')), '[]'::jsonb),
    'documents', coalesce((select jsonb_agg(jsonb_build_object('id', d.id, 'type', d.type, 'filename', d.filename, 'created_at', d.created_at, 'sha256', d.sha256))
      from public.documents d where d.machine_id = m.id and d.visibility in ('verifiers', 'public') and d.status = 'clean' and d.archived_at is null), '[]'::jsonb)
  ) || app.buyer_report_extras(m.id);
end $$;

-- Hook for fleet reports / project lists shared with clients (step 12).
create or replace function app.shared_fleet_view(s public.share_links)
returns jsonb language sql stable security definer set search_path = '' as $$ select '{}'::jsonb $$;

create or replace function public.get_share_view(p_token text, p_ip_hash text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare s public.share_links; m public.machines;
begin
  if p_ip_hash is not null and not app.rate_limit_hit('share:' || p_ip_hash, 60, interval '1 minute') then perform app.raise('RATE_LIMITED'); end if;
  select * into s from public.share_links where token_hash = app.sha256_hex(coalesce(p_token, '')) for update;
  if s.id is null then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if s.revoked_at is not null then return jsonb_build_object('ok', false, 'reason', 'revoked'); end if;
  if s.expires_at <= now() then return jsonb_build_object('ok', false, 'reason', 'expired'); end if;
  if s.max_views is not null and s.views >= s.max_views then return jsonb_build_object('ok', false, 'reason', 'max_views'); end if;
  update public.share_links set views = views + 1 where id = s.id;
  if s.machine_id is not null then
    select * into m from public.machines where id = s.machine_id;
    insert into public.access_log (machine_id, viewer_type, via, ip_hash, visible_to_owner) values (m.id, 'public', 'share_link', p_ip_hash, true);
  end if;
  return jsonb_build_object('ok', true, 'scope', s.scope, 'expires_at', s.expires_at,
    'views_left', case when s.max_views is null then null else s.max_views - s.views - 1 end,
    'shared_by', (select name from public.organizations where id = s.org_id),
    'data', case s.scope
      when 'public_card' then app.public_card_json(m, null)
      when 'buyer_report' then app.buyer_report(m.id)
      else app.shared_fleet_view(s) end);
end $$;

-- ---------- RLS ----------
alter table public.documents enable row level security;
alter table public.access_log enable row level security;
alter table public.share_links enable row level security;
revoke all on public.documents, public.access_log, public.share_links from anon, authenticated;
grant select on public.documents, public.access_log to authenticated;
grant select (id, machine_id, org_id, created_by_user_id, token_prefix, scope, params, expires_at, max_views, views, revoked_at, created_at)
  on public.share_links to authenticated;

create policy documents_read on public.documents for select to authenticated using (app.can_read_document(documents));
create policy access_log_read on public.access_log for select to authenticated using (
  app.is_operator() or app.acts_as('authority')
  or (visible_to_owner and app.machine_relations(machine_id) && array['owner', 'user'])
);
create policy share_links_read on public.share_links for select to authenticated using (org_id = any (app.current_org_ids()));

grant execute on function app.can_read_document(public.documents) to authenticated, service_role;
grant execute on function
  public.scan_label(uuid, text), public.list_access_log(uuid, uuid, int),
  public.create_document_upload(uuid, uuid, public.document_type, text, text, bigint, text, public.document_visibility),
  public.finalize_document(uuid, uuid), public.list_documents(uuid, uuid), public.set_document_visibility(uuid, uuid, public.document_visibility),
  public.archive_document(uuid, uuid), public.set_primary_photo(uuid, uuid, uuid),
  public.create_share_link(uuid, uuid, public.share_scope, int, int, jsonb), public.list_share_links(uuid, uuid),
  public.revoke_share_link(uuid, uuid), public.authorize_document_download(uuid, text)
  to authenticated;
grant execute on function public.authorize_document_download(uuid, text) to anon;
grant execute on function public.log_public_scan(text, text, text, text, jsonb), public.report_sighting(text, text, text, jsonb, text, text),
  public.get_share_view(text, text), public.record_document_scan(uuid, boolean, boolean, text) to service_role;
